README.md
=> Add API sketch and clarify data structures.

README.md
Based on conversations about SPC I thought it might be useful to start an FAQ.
I started it with a first question: 
Can the party that calls SPC validate the assertion even if not the RP?
Ian
=> FAQ: Can the party that calls SPC validate the assertion even if not the RP?

scope.md
@mweksler,
Here are the user stories we discussed, slightly edited.
@Goosth please review the "low friction" story. I mostly want to be sure to record the low friction journey you have in mind. This text may not yet do that.
Ian
=> Add some draft user stories

README.md
Both for enrollment and authentication.
=> Update explainer with cross-origin notes

scope.md
Per 10 May SPC task force discussion, this PR splits "benefits" from "features".
=> Clearer benefit/feature descriptions

spec.bs
This version of the spec is an early-draft, laying out one possible
API shape for SPC. It should not be considered final, and exists to give
spec discussions a concrete basis to debate on.
Also-by: Rouslan Solomakhin <rouslan@chromium.org>
=> [Spec] First draft version of spec

spec.bs
Looking forward to discussion of these proposed changes.
=> Editorial review of section 1

spec.bs
Many fewer suggestions than the previous PR. :)
=> Additional editorial suggestions sections 2 and beyond

spec.bs
Fixes https://github.com/w3c/secure-payment-confirmation/issues/83
=> [Spec] Add payeeOrigin

spec.bs
This commit contains a set of general improvements to the spec:
* Actually define a Payment Handler for SPC
* Add said Payment Handler to the official registry via a monkey-patch
* Properly link to IDL definitions in **many** places.
* Inline dictionary creation in the algorithms
=> [Spec] Various spec improvements

spec.bs
Co-authored-by: Dominic Farolino <dom@chromium.org>
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/pull/106.html" title="Last updated on Aug 17, 2021, 2:30 PM UTC (656d734)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/106/2205b0f...656d734.html" title="Last updated on Aug 17, 2021, 2:30 PM UTC (656d734)">Diff</a>
=> [Spec] Minor fixups suggested by domfarolino

explainer.md
@stephenmcgruer, per your observation about wanting to clarify what's in and out of the API during a typically flow, here is a simple proposal.
=> Clarify start/end of API call

spec.bs
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/pull/111.html" title="Last updated on Aug 22, 2021, 4:59 PM UTC (f530c5f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/111/44ef82b...f530c5f.html" title="Last updated on Aug 22, 2021, 4:59 PM UTC (f530c5f)">Diff</a>
=> [Spec] Write up Security & Privacy sections

spec.bs
Fixes #96
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/pull/133.html" title="Last updated on Oct 1, 2021, 8:31 PM UTC (f27214a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/133/ba809db...f27214a.html" title="Last updated on Oct 1, 2021, 8:31 PM UTC (f27214a)">Diff</a>
=> [Spec] Specify relying party operations

spec.bs
Editorial. Addresses #140.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/pull/148.html" title="Last updated on Nov 1, 2021, 8:24 PM UTC (e38961a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/148/7ddfcd8...e38961a.html" title="Last updated on Nov 1, 2021, 8:24 PM UTC (e38961a)">Diff</a>
=> Editorial: To address issue 140

spec.bs
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/pull/167.html" title="Last updated on Dec 6, 2021, 7:17 PM UTC (b3ff98c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/167/c5f5828...b3ff98c.html" title="Last updated on Dec 6, 2021, 7:17 PM UTC (b3ff98c)">Diff</a>
=> [Spec] Better define what an SPC credential is and its requirements

explainer.md
In response to various questions about how SPC works in various failure modes I've added a new section. This is a first pass and probably needs enhancements and corrections.
=> Provide high-level of UX in various failure modes

README.md
=> Update README.md - fix spelling of name

spec.bs
Fixes #168
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/pull/179.html" title="Last updated on Mar 2, 2022, 5:39 PM UTC (470e48c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/179/2d0c9a2...470e48c.html" title="Last updated on Mar 2, 2022, 5:39 PM UTC (470e48c)">Diff</a>
=> [Spec] Make example clearer about iframe interactions

.github/workflows/build.yml, spec.bs
This PR adds embedded WPT test information to the relevant spec sections.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/pull/193.html" title="Last updated on Jun 21, 2022, 10:18 PM UTC (bb1d520)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/193/efd6ab9...bb1d520.html" title="Last updated on Jun 21, 2022, 10:18 PM UTC (bb1d520)">Diff</a>
=> [Spec] Add WPT test information to the spec

spec.bs
Fixes #194
Depends on https://github.com/w3c/payment-request/pull/977
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/pull/195.html" title="Last updated on Jul 7, 2022, 5:07 PM UTC (a314305)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/195/12f96d5...a314305.html" title="Last updated on Jul 7, 2022, 5:07 PM UTC (a314305)">Diff</a>
=> [Spec] Move some input validation to construction time

spec.bs
Closes #206
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/pull/210.html" title="Last updated on Sep 14, 2022, 4:13 AM UTC (358d717)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/210/50f0e7c...358d717.html" title="Last updated on Sep 14, 2022, 4:13 AM UTC (358d717)">Diff</a>
=> [Spec] Remove example code with a hard-coded error string

accessibility-checklist.md
Takes into account opt-out (PR #215).
=> Updated for opt-out feature as part of preparing to go to CR

explainer.md
* New text on opt-out as a failure mode
* Added note and link to issue related to removal of user activation requirement.
* Some typo fixes.
=> Some changes before requesting to advance to CR

security-privacy-questionnaire.md
* Removal of user activation consumption at auth time
* Opt-out feature
=> Some updates for advancing to CR

spec.bs
Fixes #219
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/pull/221.html" title="Last updated on Jan 6, 2023, 3:04 PM UTC (a7edd49)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/221/c24f564...a7edd49.html" title="Last updated on Jan 6, 2023, 3:04 PM UTC (a7edd49)">Diff</a>
=> [Spec] Do not use WebIDL to define WebDriver parameters

spec.bs
Seeks to address #226
cc @aphillips
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Jan 30, 2023, 6:40 PM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [CSS Spec Preprocessor](https://api.csswg.org/bikeshed/) - CSS Spec Preprocessor is the web service used to build Bikeshed specs.
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Fsecure-payment-confirmation%2Fe4959d4d1ca773cac3490c720f7d95c4cfd6af2c%2Fspec.bs&md-warning=not%20ready)
```
Error running preprocessor, returned code: 2.
FATAL ERROR: Couldn't find section '#relying-party-identifier' in spec 'webauthn-3': …
```
=> Add locale to example

spec.bs
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/pull/239.html" title="Last updated on Apr 17, 2023, 3:42 PM UTC (ceeca1c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/239/fd37ebe...ceeca1c.html" title="Last updated on Apr 17, 2023, 3:42 PM UTC (ceeca1c)">Diff</a>
=> [Editorial] Recognize Nick and Ian as contributors

spec.bs
Editorial tweak based on:
https://github.com/w3c/secure-payment-confirmation/pull/232#pullrequestreview-1343877232
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/pull/234.html" title="Last updated on Apr 21, 2023, 1:39 PM UTC (4a90137)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/234/9b4ec43...4a90137.html" title="Last updated on Apr 21, 2023, 1:39 PM UTC (4a90137)">Diff</a>
=> [Editorial] Tweak to i18n considerations

spec.bs
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/pull/248.html" title="Last updated on May 25, 2023, 8:15 PM UTC (212ecbe)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/248/c3f07d2...212ecbe.html" title="Last updated on May 25, 2023, 8:15 PM UTC (212ecbe)">Diff</a>
=> [Spec] Cleanup; removed outdated notes

security-privacy-questionnaire-bbk.md
Based the w3c [Self-Review Questionnaire: Security and Privacy](https://www.w3.org/TR/security-privacy-questionnaire/)
=> Add the TAG security and privacy self-review questionnaire for BBKs.

spec.bs
Closes #301
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/pull/303.html" title="Last updated on Jun 16, 2025, 8:33 PM UTC (a2b4707)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/303/54ebe9c...a2b4707.html" title="Last updated on Jun 16, 2025, 8:33 PM UTC (a2b4707)">Diff</a>
=> [Editorial] Fix broken link

spec.bs
Moving Rouslan Solomakhin from "Editor" to "Former Editor" group.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/pull/314.html" title="Last updated on Sep 25, 2025, 8:13 PM UTC (0c334e8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/314/b6528ef...0c334e8.html" title="Last updated on Sep 25, 2025, 8:13 PM UTC (0c334e8)">Diff</a>
=> Update spec editors
