w3c/secure-payment-confirmation

- README.md
See https://github.com/w3c/secure-payment-confirmation/issues/57
> [Explainer] Mark `fallbackUrl` as deprecated

- README.md
M92 is now Chrome Stable, there should be no need for developers to specify the
fallbackUrl anymore.
Fixes #57
> [Explainer] Remove fallbackUrl entirely

- spec.bs
1. Don't set type to payment.create
Given the goal of aligning more closely with WebAuthn the use of `payment.create` instead of `webauthn.create` when creating a new credential seems arbitrary. The data scheme a is the same so there is no need to detect the type.
Also, there is no Auhtenticator extenion processing so no need for authenticators to treat this client data in a special manner.
2. Remove note re getClientExtensionResults
Since the extension defines no "Client extension output" this would always return an empty result (or am I misreading the spec?)
> Remove custom CollectedClientData handling

- spec.bs
New note with background on current shape of API and setting expectation it will change.
Relates to issues #81 and #65 (but does not close them).
> Note on API shape

- spec.bs
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/pull/105.html" title="Last updated on Aug 17, 2021, 6:54 PM UTC (90a3c28)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/105/6173bf7...90a3c28.html" title="Last updated on Aug 17, 2021, 6:54 PM UTC (90a3c28)">Diff</a>
> [Spec] Require that `payeeOrigin` is fully qualified

- spec.bs
The spec incorrectly had called the `rp` member, which is the **id** of the RP,
`rpOrigin` instead and implied it was the origin.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/pull/107.html" title="Last updated on Aug 17, 2021, 6:59 PM UTC (5e9587d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/107/10f1b5d...5e9587d.html" title="Last updated on Aug 17, 2021, 6:59 PM UTC (5e9587d)">Diff</a>
> [Spec] Bugfix: rpOrigin --> rp

- explainer.md
This commit both brings the explainer up-to-date with the current spec, and
re-writes it to follow the guidance at https://w3ctag.github.io/explainers
Part 1 includes the motivation, the proposed solution (SPC) and outlines the
JavaScript APIs.
> [Explainer] Re-write the explainer to best-practices, part 1/n

- spec.bs
This pull request comes from an issue raised by @Goosth [1] and discussed at today's SPC task force call.
[1] https://github.com/w3c/secure-payment-confirmation/pull/103
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/pull/104.html" title="Last updated on Aug 20, 2021, 2:53 PM UTC (4c5e898)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/104/44ef82b...4c5e898.html" title="Last updated on Aug 20, 2021, 2:53 PM UTC (4c5e898)">Diff</a>
> Note about credential reuse in both directions

- explainer.md
This series of commits both brings the explainer up-to-date with the current spec,
and re-writes it to follow the guidance at https://w3ctag.github.io/explainers
Part 2 adds the Security and Privacy considerations.
> [Explainer] Re-write the explainer to best-practices, part 2/n

- explainer.md
- requirements.md
- scope.md
- spec.bs
In alignment with Web Authentication, use "registration" instead of "enrollment":
https://w3c.github.io/webauthn/#sctn-usecase-registration
This is an editorial change with no impact on the API / deployed code.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/pull/115.html" title="Last updated on Aug 23, 2021, 6:08 PM UTC (52017db)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/115/5906d61...52017db.html" title="Last updated on Aug 23, 2021, 6:08 PM UTC (52017db)">Diff</a>
> Registration instead of Enrollment

- explainer.md
This series of commits both brings the explainer up-to-date with the current spec,
and re-writes it to follow the guidance at https://w3ctag.github.io/explainers
Part 3 adds the Other Considerations and Alternatives explored.
> [Explainer] Re-write the explainer to best-practices, part 3/n

- spec.bs
- status-ED.include
- status-FPWD.include
- status-WD.include
* Updates some metadata in spec.bs for W3C pubrules (but leaves Status as ED)
* Adds some boilerplate for Status Section of upcoming FPWD, subsequent EDs, and subsequent WDs
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/pull/118.html" title="Last updated on Aug 24, 2021, 2:07 PM UTC (0ba14d5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/118/7abc234...0ba14d5.html" title="Last updated on Aug 24, 2021, 2:07 PM UTC (0ba14d5)">Diff</a>
> Preparing for FPWD (and then auto-publishing)

- spec.bs
Addresses issue #119
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/pull/120.html" title="Last updated on Aug 25, 2021, 10:13 PM UTC (320ac6c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/120/24997c1...320ac6c.html" title="Last updated on Aug 25, 2021, 10:13 PM UTC (320ac6c)">Diff</a>
> Speak to current implementation limitation regarding userVerification

- .github/workflows/build.yml
- spec.bs
These were previously incorrect specified as auth-time requirements, but they
are actually registration time arguments. This was overlooked as the build
action didn't fail on warnings by default. This commit also changes the action
to fail in such cases.
Fixes #129
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/pull/132.html" title="Last updated on Oct 1, 2021, 2:56 PM UTC (9c9d0b7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/132/0444d4c...9c9d0b7.html" title="Last updated on Oct 1, 2021, 2:56 PM UTC (9c9d0b7)">Diff</a>
> [Spec] Correctly specify authenticatorSelection requirements

- spec.bs
New text to cover the attack where a caller intentionally or accidentally calls the API
with an instrument string and completely unrelated (but valid) SPC credentials.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/pull/155.html" title="Last updated on Nov 2, 2021, 9:52 PM UTC (3d4204e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/155/4015745...3d4204e.html" title="Last updated on Nov 2, 2021, 9:52 PM UTC (3d4204e)">Diff</a>
> Describe protections against "wrong credential" attack

- spec.bs
* Point out that "user" info is not part of SPC, and
* Heads up on consistent usage to avoid credential
selection as discussed in the SPC TF:
https://www.w3.org/2021/11/08-wpwg-spc-minutes#t01
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/pull/158.html" title="Last updated on Nov 10, 2021, 5:19 PM UTC (2232725)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/158/cd8781c...2232725.html" title="Last updated on Nov 10, 2021, 5:19 PM UTC (2232725)">Diff</a>
> Enhanced note about role of user data in example

- spec.bs
Partially addresses #69.
It seems that issue 69 is addressed by the specification, which says to follow a credential management API algorithm. However, since that is not what the current Chrome implementation does, I propose to add an implementation note.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/pull/159.html" title="Last updated on Nov 12, 2021, 8:29 PM UTC (f1e771c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/159/14e5471...f1e771c.html" title="Last updated on Nov 12, 2021, 8:29 PM UTC (f1e771c)">Diff</a>
> Implementation note related to N matching credentials

- spec.bs
Addresses #127 
Guidance to use the displayName to ensure accessibility.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/pull/162.html" title="Last updated on Nov 12, 2021, 10:32 PM UTC (b6423ce)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/162/9ec6e5a...b6423ce.html" title="Last updated on Nov 12, 2021, 10:32 PM UTC (b6423ce)">Diff</a>
> Using displayName for icon accessibility

- spec.bs
As per
https://github.com/w3c/secure-payment-confirmation/issues/149#issuecomment-944130133,
the correct syntax for WebIDL dictionary access is square brackets, not the dot
operator.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/pull/161.html" title="Last updated on Nov 15, 2021, 2:38 PM UTC (b33d207)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/161/9ec6e5a...b33d207.html" title="Last updated on Nov 15, 2021, 2:38 PM UTC (b33d207)">Diff</a>
> [Spec] Editorial: Get rid of "dot" notation for dictionaries

- spec.bs
Fixes #149
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/pull/160.html" title="Last updated on Nov 15, 2021, 5:07 PM UTC (8a23d12)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/160/8fbbe76...8a23d12.html" title="Last updated on Nov 15, 2021, 5:07 PM UTC (8a23d12)">Diff</a>
> [Spec] Correctly validate payeeOrigin

- spec.bs
This adds an option to the SecurePaymentConfirmationRequest for the
developer to allow the credential to still be authenticated if the
payment instrument icon fails to download or decode. This is done by
adding an attribute `iconMustBeShown` to the
`PaymentCredentialInstrument`.
The algorithms to check, display, and respond to a request are updated
accordingly.
Issue #125
***
<a href="https://pr-preview.s3.amazonaws.com/nickburris/secure-payment-confirmation/pull/171.html" title="Last updated on Feb 1, 2022, 3:12 PM UTC (1a94537)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/171/edcdaa5...nickburris:1a94537.html" title="Last updated on Feb 1, 2022, 3:12 PM UTC (1a94537)">Diff</a>
> Add option to allow instrument icon download fail

- spec.bs
The example was misleading, as it is already explicitly disallowed by the spec
(see 4.1.4, step 8). Removing it hopefully makes it clear that 11.2 is about a
general class of risk that SPC (and WebAuthn) has as a technology, not a
specific attack with a specific mitigation.
See #142
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/pull/176.html" title="Last updated on Mar 2, 2022, 3:49 PM UTC (f7601f8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/176/97f5847...f7601f8.html" title="Last updated on Mar 2, 2022, 3:49 PM UTC (f7601f8)">Diff</a>
> [Spec] Remove example from 11.2

- spec.bs
This section still contained an idea outline (for salting credential IDs) from
when the spec was in its development phrase. The actual idea is in issue #77
and shouldn't be part of the spec itself.
Also added a short paragraph on a possible user mitigation for 11.3, creating
distinct user accounts.
See #143
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/pull/177.html" title="Last updated on Mar 2, 2022, 5:12 PM UTC (23880e0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/177/97f5847...23880e0.html" title="Last updated on Mar 2, 2022, 5:12 PM UTC (23880e0)">Diff</a>
> [Spec] Remove outdated write-up from 11.3

- spec.bs
Per the proposal in https://github.com/w3c/secure-payment-confirmation/issues/163, add a payeeName field to the spec.
***
<a href="https://pr-preview.s3.amazonaws.com/nickburris/secure-payment-confirmation/pull/180.html" title="Last updated on Mar 16, 2022, 6:54 PM UTC (132dd9c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/180/72907d8...nickburris:132dd9c.html" title="Last updated on Mar 16, 2022, 6:54 PM UTC (132dd9c)">Diff</a>
> Add payeeName input to spec

- spec.bs
To help mitigate confusion, propose a note on the meaning of canMakePayment in case of SPC
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/pull/181.html" title="Last updated on Apr 7, 2022, 6:27 PM UTC (61cf3d1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/181/654c78a...61cf3d1.html" title="Last updated on Apr 7, 2022, 6:27 PM UTC (61cf3d1)">Diff</a>
> Add a note in example on meaning of canMakePayment

- spec.bs
Before this PR, the spec was vague about the timing attack and also didn't
specify at all that an implementation must return a NotAllowedError instead of
the normal PaymentRequest NotSupportedError in the case of
no-matching-credentials. Whilst we don't want to enforce that UAs show a dialog
here (they may decide, for example, that a delayed response instead is
sufficiently privacy preserving), this PR does try to make the actual concern
clearer and more normative, and add a normative requirement for the return
value.
Should also improve the situation called out in
https://github.com/w3c/secure-payment-confirmation/issues/142
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/pull/182.html" title="Last updated on Apr 27, 2022, 2:01 PM UTC …
> [Spec] Be clearer about authentication ceremony privacy in 4.1.4

- spec.bs
Requested by PING in issue #142
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/pull/188.html" title="Last updated on May 4, 2022, 4:42 PM UTC (3fd6578)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/188/874d9d6...3fd6578.html" title="Last updated on May 4, 2022, 4:42 PM UTC (3fd6578)">Diff</a>
> [Spec] Add link from 11.2 to 4.1.4

- spec.bs
Android currently does not support discoverable credentials, and so will reject
credential creation if residentKey is set to 'required'. Allowing 'preferred'
as a value allows credential creation on Android.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/pull/196.html" title="Last updated on Aug 5, 2022, 8:43 PM UTC (5cbf99f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/196/248a60a...5cbf99f.html" title="Last updated on Aug 5, 2022, 8:43 PM UTC (5cbf99f)">Diff</a>
> [Spec] Allow either required or preferred for residentKey

- security-privacy-questionnaire.md
This is a minor update to take into account the revised template. I expect to work with the editors
to review and potentially update our answers as part of planning to advance to CR.
* Update sections based on 16 December 2021 Self-review questionnaire
https://www.w3.org/TR/2021/NOTE-security-privacy-questionnaire-20211216/
* Minor editorial tweaks to align with grammar of new titles.
> Updating privacy self-review questionnaire responses 

- spec.bs
See https://github.com/whatwg/webidl/issues/900
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/pull/201.html" title="Last updated on Aug 12, 2022, 2:10 PM UTC (70cdc6a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/201/279b7a3...70cdc6a.html" title="Last updated on Aug 12, 2022, 2:10 PM UTC (70cdc6a)">Diff</a>
> [Spec] Dictionary members should be sequence not FrozenArray

- spec.bs
To align with WebAuthn, we should use the term rpId here. This is a breaking
change, but implementations can mitigate the breakage by continuing to include
the old 'rp' name going forwards.
See https://github.com/w3c/secure-payment-confirmation/issues/191
Test changes: https://github.com/web-platform-tests/wpt/pull/35602
Implementation bugs:
- Chrome: https://crbug.com/1356224
- Safari: N/A
- Firefox: N/A
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/pull/198.html" title="Last updated on Aug 24, 2022, 3:49 PM UTC (dd14bfa)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/198/7204dc0...dd14bfa.html" title="Last updated on Aug 24, 2022, 3:49 PM UTC (dd14bfa)">Diff</a>
> [Spec] Rename rp --> rpId in CollectedClientAdditionalPaymentData

- spec.bs
Conversations with i18n representatives revealed that we likely don't need support for unpaired surrogates in the SPC API, and so it is simpler to align on USVStrings (rather than mixing DOMString and USVString).
Fixes https://github.com/w3c/secure-payment-confirmation/issues/208
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/pull/211.html" title="Last updated on Sep 14, 2022, 4:03 AM UTC (d6a08bd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/211/50f0e7c...d6a08bd.html" title="Last updated on Sep 14, 2022, 4:03 AM UTC (d6a08bd)">Diff</a>
> [Spec] Use USVString rather than DOMString

- spec.bs
This hint may (in an RFC2119 sense) be used by the browser to localize the SPC UX in order to match what the website is (reportedly) using in its interactions with the user.
Fixes https://github.com/w3c/secure-payment-confirmation/issues/209
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/pull/212.html" title="Last updated on Sep 17, 2022, 2:34 AM UTC (ff031ed)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/212/50f0e7c...ff031ed.html" title="Last updated on Sep 17, 2022, 2:34 AM UTC (ff031ed)">Diff</a>
> [Spec] Add SecurePaymentConfirmationRequest.locale

- spec.bs
SPC already has mitigations against on-path attacks, where an attacker positions themselves between the user and a valid merchant website. However we did not previously explain how a Relying Party can detect this, so add a line about it.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/pull/214.html" title="Last updated on Nov 9, 2022, 2:09 PM UTC (ea9b1b0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/214/63cfc2a...ea9b1b0.html" title="Last updated on Nov 9, 2022, 2:09 PM UTC (ea9b1b0)">Diff</a>
> [Spec] Expand 'payment attack' section for on-path attacks

- spec.bs
This PR adds spec text for a new showOptOut option in the SecurePaymentConfirmationRequest API. See the original proposal and discussion in #172. This spec change reflects the prototype currently implemented behind a flag in Chrome, which is available via origin trial and used in [this test page](https://rsolomakhin.github.io/pr/spc-opt-out/).
The OptOutError mentioned in this change is being added to WebIDL in https://github.com/whatwg/webidl/pull/1231.
Opt-out web platform test: https://github.com/web-platform-tests/wpt/pull/37012
***
<a href="https://pr-preview.s3.amazonaws.com/nickburris/secure-payment-confirmation/pull/215.html" title="Last updated on Dec 9, 2022, 1:49 PM UTC (78e2553)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/215/06a0 …
> Add showOptOut option to spec

- spec.bs
Fixes #225
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Jan 30, 2023, 6:23 PM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [CSS Spec Preprocessor](https://api.csswg.org/bikeshed/) - CSS Spec Preprocessor is the web service used to build Bikeshed specs.
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Fsecure-payment-confirmation%2F1f8ef791779f28a86db96436e87cdf26971e9e63%2Fspec.bs&md-warning=not%20ready)
```
Error running preprocessor, returned code: 2.
FATAL ERROR: Couldn't find section '#relying-party-identifier' in spec 'webauthn-3': …
```
> [Spec] Fix some broken refs

- spec.bs
During PING review of the pre-CR changes to SPC, the PING raised a concern that removing the user activation requirement (see https://github.com/w3c/secure-payment-confirmation/pull/236) could lead to sites triggering SPC from a background tab. This PR adds logic to the [steps to check if a payment can be made](https://w3c.github.io/payment-request/#dfn-steps-to-check-if-a-payment-can-be-made) to disallow background tabs (and minimized-windows/etc).
It is likely that eventually we will want this specified in Payment Request instead, both because it will be clearer spec text (here we have to refer to a `this` that is actually from the Payment Request spec), and also because we (in Chrome) already do (afaik) reject Payment Requests from background tabs. (Which is allowable by abusing the …
> [Spec] Only allow SPC authentication if in a foreground tab

- spec.bs
See issue #216 for context. This removes the only reference to user activation for SPC authentication, and adds some spec text giving the user agent the option to skip or relax the user activation requirement in the `PaymentRequest.show()` steps.
***
<a href="https://pr-preview.s3.amazonaws.com/nickburris/secure-payment-confirmation/pull/236.html" title="Last updated on Apr 24, 2023, 2:38 PM UTC (d5a3f40)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/236/ad27442...nickburris:d5a3f40.html" title="Last updated on Apr 24, 2023, 2:38 PM UTC (d5a3f40)">Diff</a>
> Relax user activation requirement for authentication

- explainer.md
Per TAG review [1], adding a note to Security Considerations about the click-jacking risk and how the browser mitigates it.
[1] https://github.com/w3ctag/design-reviews/issues/802#issuecomment-1422225875
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/pull/230.html" title="Last updated on Apr 24, 2023, 2:58 PM UTC (f323fbe)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/230/1565e06...f323fbe.html" title="Last updated on Apr 24, 2023, 2:58 PM UTC (f323fbe)">Diff</a>
> Note in explainer re: user activation (removal)

- spec.bs
Add to an informative Note that WebAuthn Levels 1 and 2 do not support cross-origin registration, but level 3 is expected to, and link to pull request:
https://github.com/w3c/webauthn/pull/1801
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/pull/243.html" title="Last updated on May 10, 2023, 7:59 PM UTC (058f277)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/243/8efa6ae...058f277.html" title="Last updated on May 10, 2023, 7:59 PM UTC (058f277)">Diff</a>
> Editorial: Mention WebAuthn Level 3 is expected to support cross-orgin registration

- spec.bs
The TODO to remove the 'isPayment' method is redundant. As long as we have a create-time extension, we need some sort of member to set in the dictionary, and the boolean 'isPayment' fits the same pattern as other extensions use in WebAuthn (e.g., see the credProps extension -
https://w3c.github.io/webauthn/#sctn-authenticator-credential-properties-extension)
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/pull/244.html" title="Last updated on May 23, 2023, 4:28 PM UTC (a1a1980)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/244/f1f750a...a1a1980.html" title="Last updated on May 23, 2023, 4:28 PM UTC (a1a1980)">Diff</a>
> [Spec] Remove a redundant TODO

- spec.bs
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/pull/245.html" title="Last updated on May 23, 2023, 5:03 PM UTC (658ae5d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/245/f1f750a...658ae5d.html" title="Last updated on May 23, 2023, 5:03 PM UTC (658ae5d)">Diff</a>
> [Spec] Make it clear that browsers cache just credential IDs

- spec.bs
This CL fixes a long overdue TODO to modify the PaymentRequest object's
constructor in order to make sure that if SPC is specified, then it is the only
specified payment method.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/pull/247.html" title="Last updated on May 25, 2023, 4:13 PM UTC (98bf6fd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/247/c3f07d2...98bf6fd.html" title="Last updated on May 25, 2023, 4:13 PM UTC (98bf6fd)">Diff</a>
> [Spec] Fix TODO to modify Payment Request constructor

- spec.bs
This adds spec text for an API for developers to more easily check whether SPC is available. Fixes #81. One question is whether the spec should further clarify what it means for SPC to be available, but I'm not sure how we can say that without being too implementation specific.
***
<a href="https://pr-preview.s3.amazonaws.com/nickburris/secure-payment-confirmation/pull/233.html" title="Last updated on Apr 11, 2023, 7:31 PM UTC (484e07a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/233/568fbab...nickburris:484e07a.html" title="Last updated on Apr 11, 2023, 7:31 PM UTC (484e07a)">Diff</a>
> Add isSecurePaymentConfirmationAvailable API to spec

- spec.bs
Propose to remote note based on IANA registry conversation.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/pull/255.html" title="Last updated on Jul 31, 2023, 1:58 PM UTC (b12ed5b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/255/200fb61...b12ed5b.html" title="Last updated on Jul 31, 2023, 1:58 PM UTC (b12ed5b)">Diff</a>
> Remove note around Payment extension

- spec.bs
Based on TPAC discussion of differing implementation behaviors, it could be useful to let SPC API users know about current implementation state. We plan to discuss this with the Web Authentication WG as well.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/pull/261.html" title="Last updated on Oct 18, 2023, 2:34 PM UTC (07a5911)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/261/591428a...07a5911.html" title="Last updated on Oct 18, 2023, 2:34 PM UTC (07a5911)">Diff</a>
> (Informative) Note about WebAuthn registration display behaviors (as of Oct 2023)

- spec.bs
Based on discussion about default values from SPC integration into MDN.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/pull/265.html" title="Last updated on Dec 7, 2023, 8:56 PM UTC (7656f90)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/265/5a27628...7656f90.html" title="Last updated on Dec 7, 2023, 8:56 PM UTC (7656f90)">Diff</a>
> Add reference to timeout information in WebAuthn 

- bbk-requirements.md
This is a first draft resulting from discussions within the Web Payment Security IG (during TPAC) and the [10 October 2024 WPWG meeting](https://www.w3.org/2024/10/10-wpwg-minutes#9318). 
This proposal is intended to inform discussion of #271.
> Creation of BBK requirements document

- spec.bs
This is a very minor change that is close to editorial, though it technically fixes a spec bug in "4.1.9 Steps to check if a payment can be made". Previously step 3.2 of that section only checked for an SPC Credential, not a third-party enabled SPC credential.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/pull/280.html" title="Last updated on Feb 7, 2025, 6:17 PM UTC (9d6aa9c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/280/0e2e5c5...9d6aa9c.html" title="Last updated on Feb 7, 2025, 6:17 PM UTC (9d6aa9c)">Diff</a>
> [Spec] Separate 'SPC credential' from 'third-party enabled SPC credential'

- spec.bs
The WebAuthn specification now allows credential creation in a cross origin iframe, as of https://github.com/w3c/webauthn/pull/1801. As such, SPC no longer needs to override or add this behavior.
We do retain (for now) the ability for the `"payment"` permission policy to allow credential create in an iframe, instead of requiring `"publickey-credentials-create"`. This should be removed one day, but one small step to unification at a time :).
There is a small web-compat issue here. In the case of no transient user activation, the SPC specification used to throw a `SecurityError` error. However WebAuthn throws a `NotAllowed` error instead. See also Chrome bug https://crbug.com/41484826
Fixes #267
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/pull/281.html" …
> [Spec] Remove references to create in cross origin iframe

- spec.bs
This section had only 1 subsection, "Payment Method: Secure Payment Confirmation", and we do not expect to add any more sections. As such, we can unnest it for readability.
This change does move some text around, but is editorial in that it contains no behavior changes to the specification.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/pull/291.html" title="Last updated on May 5, 2025, 9:07 PM UTC (06325af)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/291/f3a890d...06325af.html" title="Last updated on May 5, 2025, 9:07 PM UTC (06325af)">Diff</a>
> [Spec] Un-nest section 4 (Authentication)

- spec.bs
See #271
***
<a href="https://pr-preview.s3.amazonaws.com/pejic/secure-payment-confirmation/pull/286.html" title="Last updated on Jun 5, 2025, 5:16 PM UTC (c527dbf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/286/c7dd82e...pejic:c527dbf.html" title="Last updated on Jun 5, 2025, 5:16 PM UTC (c527dbf)">Diff</a>
> Add browser binding to the secure payment confirmation spec

- spec.bs
This change adds privacy and security considerations related to browser bound keys. See also #286 for the implementation.
***
<a href="https://pr-preview.s3.amazonaws.com/pejic/secure-payment-confirmation/pull/296.html" title="Last updated on May 22, 2025, 8:30 PM UTC (2ad6dab)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/296/72eb74e...pejic:2ad6dab.html" title="Last updated on May 22, 2025, 8:30 PM UTC (2ad6dab)">Diff</a>
> [Spec] Add browser bound keys privacy and security considerations.

- spec.bs
***
<a href="https://pr-preview.s3.amazonaws.com/pejic/secure-payment-confirmation/pull/308.html" title="Last updated on Jul 16, 2025, 12:48 PM UTC (cd36f70)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/308/7806432...pejic:cd36f70.html" title="Last updated on Jul 16, 2025, 12:48 PM UTC (cd36f70)">Diff</a>
> Add wpt tests for browser bound keys and auth another way.
